name: S3 custom action test

on:
 workflow_dispatch:

jobs:
  s3_file_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Upload and Download File from S3
        uses: sheikhasim/s3-upload-test-action@v23.2.4
        with:
          aws-role-arn: "arn:aws:iam::053869304403:role/asishe-GH-role"
          aws-region: ${{secrets.AWS_REGION}}
          file-to-upload: './subgraphs/sb1.graphql'
          s3-bucket: ${{secrets.AWS_S3_BUCKET}}
          s3-upload-key: 'schema-reg1/sb1.graphql'
          s3-download-key: 'schema-reg1/sb1.graphql'
          downloaded-file-path: './subgraphs/download'

      - name: Display Uploaded and Downloaded File
        run: |
          echo "Uploaded File:"
          cat ./subgraphs/upload/sb1.graphql
          echo "Downloaded File:"
          cat ./subgraphs/download/sb1.graphql
