name: Trigger PF-schema check workflow

on:
  pull_request:
    paths:
      - 'subgraphs/sb1.graphql'
  workflow_dispatch:

jobs:
  trigger_pf_workflow:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for aws oidc connection
      contents: read # This is required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: GitHub-OIDC
          aws-region: ${{ secrets.AWS_REGION }}
          mask-aws-account-id: true

      - name: Trigger and wait
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: sheikhasim
          repo: graphql-demo-PF
          github_token: ${{ secrets.ACCESS_TOKEN }}
          workflow_file_name: schema_check.yml
          client_payload: '{"subgraph": "./subgraphs/sb1.graphql"}'
          wait_interval: 10
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true

      - name: Sync files to S3 bucket
        run: |
            aws s3 sync ./subgraphs s3://${{secrets.AWS_S3_BUCKET}} --delete

        

