name: Trigger PF-schema check workflow on PR 

on:
  pull_request_target:
    types:
      opened
    paths:
      - 'subgraphs/sb1.graphql'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read 

jobs:
  trigger_pf_workflow:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

   
      - name: Trigger and wait
        id: schema_checks
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: sheikhasim
          repo: graphql-demo-PF
          github_token: ${{ secrets.ACCESS_TOKEN }}
          workflow_file_name: schema_check.yml
          #client_payload: '{"subgraph": "subgraphs/sb1.graphql"}'
          wait_interval: 10
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true
          
      #- name: Sync files to S3 bucket
       # run: |
           #aws s3 sync ./subgraphs s3://${{ secrets.AWS_S3_BUCKET }} --delete
      
